Create kip-84.md
Kwenta/kwenta-state-log pull request #29
Opened 2023-05-31 17:27 UTC by BurtRock

2023-05-31 21:55 UTC, platschi requested changes

2023-05-31 21:55 UTC, platschi commented on kips/kip-84.md
> +section: 1
Should be `section: 4`

2023-06-08 13:11 UTC, Marko-roy approved these changes

2023-06-08 13:16 UTC, platschi approved these changes

2023-06-08 13:16 UTC, merged