Kip 100
Kwenta/kwenta-state-log pull request #55
Opened 2023-09-25 20:04 UTC by JaredBorders

2023-09-25 22:00 UTC, JChiaramonte7 requested changes

2023-09-25 22:00 UTC, JChiaramonte7 commented on kips/kip-100.md
> +Smart Margin v3 (SMv3) will serve as Kwenta's on-chain margin engine for trading derivatives powered by Synthetix v3. SMv3 will handle all trades created on the platform and serve as a single entry p
Prefer `onchain` vs `on-chain`

2023-09-25 22:00 UTC, JChiaramonte7 commented on kips/kip-100.md
> +Conditional Orders specify both order details (`IEngine.OrderDetails`) and on-chain verification criteria. This bundled data (`IEngine.ConditionalOrder`) is signed off-chain by the account owner and
Would link to these contracts or paste struct interface here

2023-09-25 22:00 UTC, JChiaramonte7 commented on kips/kip-100.md
> +Multi-leg interactions within a single transaction are possible, similar to SMv2, thanks to its multicallable feature. However, authorization is needed for the engine to access these accounts, which
Setting account permissions on Synthetix contracts or ours? I'm assuming theirs, but not clear here.

Also, is the margin engine itself something that needs to be granted permission to by the original user?

2023-09-26 16:54 UTC, JaredBorders commented on kips/kip-100.md
> +Conditional Orders specify both order details (`IEngine.OrderDetails`) and on-chain verification criteria. This bundled data (`IEngine.ConditionalOrder`) is signed off-chain by the account owner and
Added struct

2023-09-26 16:54 UTC, JaredBorders commented on kips/kip-100.md
> +Multi-leg interactions within a single transaction are possible, similar to SMv2, thanks to its multicallable feature. However, authorization is needed for the engine to access these accounts, which
Added clarification

2023-09-26 20:04 UTC, platschi approved these changes

2023-09-26 20:04 UTC, merged